# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  redis:
    ports:
      - "5379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
  

  postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)


  identity:
    environment:
      # - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IdentityUrl=http://identity
      - BasketUrl=http://basketservice
      - WebServerUrl=https://webserver:9000/callback/login/local
      # - WebServerUrl=https://openidconnect.net/callback
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/identity.pfx
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=changeit
    ports:
      - 7004:80
      - 443
    volumes:
      - ./cert/identity.pfx:/https/identity.pfx:ro


  identity-dapr:
    command: ["./daprd",
      "-app-id", "identity",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  basketservice:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=https://identity
    ports:
      - 7002:80
    depends_on:
      - redis

  basketservice-dapr:
    depends_on:
      - basketservice
    command: ["./daprd",
      "-app-id", "basketservice",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]

    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  orderservice:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - 7003:80
    depends_on:
      - redis

  orderservice-dapr:
    depends_on:
      - orderservice
    command: ["./daprd",
      "-app-id", "orderservice",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]

    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
