# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  redis:
    ports:
      - "5379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  basketservice:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - 7002:80
    depends_on:
      - redis

  basketservice-dapr:
    depends_on:
      - basketservice
    command: ["./daprd",
      "-app-id", "basketservice",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]

    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  orderservice:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - 7003:80
    depends_on:
      - redis

  orderservice-dapr:
    depends_on:
      - orderservice
    command: ["./daprd",
      "-app-id", "orderservice",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]

    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"