# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  redis:
    image: redis:alpine
    ports:
      - "5379:6379"

  rabbitmq:
      image: rabbitmq:3-management-alpine


  basketservice:
    image: mydaprbasket
    build:
      context: .
      dockerfile: src/mydapr.Basket/Dockerfile
    depends_on:
      - redis
      - rabbitmq

  basketservice-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:basketservice"
    depends_on:
      - basketservice

  orderservice:
    image: mydaprorder
    build:
      context: .
      dockerfile: src/mydapr.Order/Dockerfile
    depends_on:
      - basketservice
      - rabbitmq

  orderservice-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:orderservice"
    depends_on:
      - orderservice