# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mydaprapiservice:
    image: mydaprapiservice
    build:
      context: .
      dockerfile: src/mydapr.ApiService/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7001:7001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
